"""add created_at to projects

Revision ID: 5020472ecf8e
Revises: 67e591d6fca4
Create Date: 2026-02-13 20:33:06.244663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5020472ecf8e'
down_revision: Union[str, Sequence[str], None] = '67e591d6fca4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'created_at')
    # ### end Alembic commands ###
